#!/usr/bin/env bash
# hooks/shell/post-install.sh — shell environment wiring.
#
# IDEMPOTENCE: exactly one line is appended to each rc file, inside a marker
# block, and it sources a single generated file. Re-running never accumulates
# duplicates, and uninstall.sh removes the block cleanly. The alternative —
# appending export lines directly — is how dotfiles rot.
set -Eeuo pipefail
# shellcheck source=../../lib/common.sh
. "$(cd -P "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/lib/common.sh"

SHELLENV="$AI_DATA_DIR/shellenv.sh"
mkdir -p "$(dirname "$SHELLENV")"

cat > "$SHELLENV" <<'SHELLENV_EOF'
# Generated by vibe-coding-tools. Do not edit; regenerate with `ai install`.
# shellcheck shell=bash

# --- PATH -------------------------------------------------------------------
case ":${PATH}:" in
  *":${HOME}/.local/bin:"*) : ;;
  *) PATH="${HOME}/.local/bin:${PATH}" ;;
esac
case ":${PATH}:" in
  *":${HOME}/.cargo/bin:"*) : ;;
  *) [ -d "${HOME}/.cargo/bin" ] && PATH="${HOME}/.cargo/bin:${PATH}" ;;
esac
export PATH

# --- vibe-coding-tools directories -----------------------------------------
export AI_HOME="${HOME}/.ai"

# --- Node via fnm (user space, so npm -g never needs sudo) ------------------
# Keep the stable default path as a non-interactive fallback. fnm's environment
# then adds version switching for interactive shells.
for fnm_root in "${XDG_DATA_HOME:-${HOME}/.local/share}/fnm" "${HOME}/.local/share/fnm" "${HOME}/.fnm"; do
  if [ -x "${fnm_root}/fnm" ]; then
    PATH="${fnm_root}/aliases/default/bin:${fnm_root}:${PATH}"
    break
  fi
done
export PATH
unset fnm_root
if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env --use-on-cd --shell bash 2>/dev/null)" || true
fi

# --- zoxide -----------------------------------------------------------------
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init bash 2>/dev/null)" || true
fi

# --- Ubuntu renames: fd is fdfind, bat is batcat ---------------------------
command -v fd  >/dev/null 2>&1 || { command -v fdfind >/dev/null 2>&1 && alias fd=fdfind; }
command -v bat >/dev/null 2>&1 || { command -v batcat >/dev/null 2>&1 && alias bat=batcat; }

# --- agent aliases ----------------------------------------------------------
command -v claude   >/dev/null 2>&1 && alias cc='claude'
command -v codex    >/dev/null 2>&1 && alias cx='codex'
command -v opencode >/dev/null 2>&1 && alias oc='opencode'

# --- telemetry opt-out ------------------------------------------------------
# Enabled by default (AI_OPT_OUT_TELEMETRY=1). Several components in this stack
# phone home unless told not to; on a work machine that should be a deliberate
# choice, not a default you never saw.
if [ "${AI_OPT_OUT_TELEMETRY:-1}" = "1" ]; then
  export DO_NOT_TRACK=1
  export CODEGRAPH_TELEMETRY=0
  export SUPERPOWERS_DISABLE_TELEMETRY=1
  export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
fi

# --- completions ------------------------------------------------------------
if [ -n "${BASH_VERSION:-}" ] && command -v aistack >/dev/null 2>&1; then
  eval "$(aistack completion bash 2>/dev/null)" || true
fi
SHELLENV_EOF

log_ok "generated ${SHELLENV}"

BLOCK=". \"${SHELLENV}\""
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  [[ -f "$rc" ]] || continue
  marker_block_write "$rc" "vibe-coding-tools" "$BLOCK"
  log_ok "wired ${rc}"
done
